config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  # get 'garage_booking/index'
  # get 'garage_booking/edit'
  # get 'garage_booking/update'
  
  root to: 'home#index'
  get "/about", to: "home#about"

  authenticate :user, lambda { |u| u.car_owner? } do
    resources :cars do
      resources :bookings, shallow: true
    end
  end

  authenticate :user, lambda { |u| u.garage_admin? } do
    resources :garages, only: [:index, :show] do
      resources :bookings, only: [:index, :edit, :update], controller: 'garage_bookings' do
        resources :invoices, only: [:show]
      end
    end
    

  end


  # API routes
  namespace :api do
    namespace :v1 do 
      get 'home', to: 'home#index'
      get 'about', to: 'home#about'
      
      resources :cars do
        resources :bookings, shallow: true
      end
      resources :garages, only: [:index, :show] do
        resources :bookings, only: [:index, :edit, :update], controller: 'garage_bookings' do
          resources :invoices, only: [:show]
        end
      end
      resource :garage_vehicle_brands, only: [:show, :update], path: 'garage-vehicle-brands'
      resources :service_types, only: [:index, :show]
      resources :vehicle_brands, only: [:index]
      resources :users, only: [:show, :update]
    end
  end
    
  mount ActionCable.server => '/cable'
  
  get "up" => "rails/health#show", as: :rails_health_check

end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="ar">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_include_tag "api_auth", "data-turbo-track": "reload", defer: true %>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.rtl.min.css" integrity="sha384-Xbg45MqvDIk1e563NLpGEulpX6AvL404DP+/iCgW9eFa2BqztiwTexswJo2jLMue" crossorigin="anonymous">

    <title>Mechanico</title>
    
  </head>
  <body>
    <!-- Flash messages -->
    <% if notice %>
      <div class="alert alert-success text-center"><%= notice %></div>
    <% end %>

    <% if alert %>
      <div class="alert alert-danger text-center"><%= alert %></div>
    <% end %>


    <!-- Navbar (already styled as you provided) -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary shadow-sm">
      <div class="container-fluid">
        <%= link_to "Mechanico", root_path, class: "navbar-brand fw-bold" %>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" 
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to "Home", root_path, class: "nav-link active", aria: { current: "page" } %>
            </li>
            <li class="nav-item">
              <%= link_to "About", about_path, class: "nav-link" %>
            </li>
            <% if user_signed_in? %>
              <% if current_user.car_owner? %>
                <li class="nav-item">
                  <%= link_to "My Cars", cars_path, class: "nav-link" %>
                </li>
              <% elsif current_user.garage_admin? %>
                <li class="nav-item">
                  <%= link_to "My Garage", garages_path, class: "nav-link" %>
                </li>
              <% end %>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>


    <!-- Main content -->
    <div class="text-end px-3 py-2 bg-light">
      <% if user_signed_in? %>
         Hello, <%= current_user.name %> |
        <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: "btn btn-sm btn-outline-danger ms-2" %>
        <%= javascript_tag do %>
          document.addEventListener('DOMContentLoaded', function() {
            var logoutButton = document.querySelector('form[action*="sign_out"]');
            if (logoutButton) {
              logoutButton.addEventListener('submit', function() {
                sessionStorage.removeItem('access_token');
                localStorage.removeItem('access_token')
              });
            }
          });
        <% end %>
      <% else %>
        <%# <%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-sm btn-primary me-2" %> 
        <%= link_to 'Login', new_user_session_path, class: "btn btn-sm btn-outline-primary" %>
      <% end %>
    </div>




    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.min.js" integrity="sha384-7qAoOXltbVP82dhxHAUje59V5r2YsVfBafyUDxEdApLPmcdhBPg1DKg1ERo0BZlK" crossorigin="anonymous"></script>
    -->

    <%= yield %>
  </body>
</html>